### ISSUE TITLE
Jetson Board Mismatch

### ISSUE THREAD

**Issue by wikpunGitHub** [JetsonHacksNano/rootOnUSB#9]
`jetbot@jetbot:~$ cd rootOnUSB/
jetbot@jetbot:~/rootOnUSB$ ./buildKernel.sh
Jetson Model: jetson-nano
Jetson L4T: 32.1.0
Installing buildModulesAndKernel
Cloning into '/home/jetbot/buildKernelAndModules'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 69 (delta 39), reused 51 (delta 27), pack-reused 0
Unpacking objects: 100% (69/69), done.
Proposed source path: /usr/src/kernel/kernel-4.9
Jetson Model: jetson-nano
Getting L4T Version
 Jetson BSP Version:  L4T R32.1.0
Jetson_L4T=32.1.0
==== Jetson Board Mismatch! =============
Currently this script works for the NVIDIA Jetson Nano Developer Kit.
This processor appears to be a jetson-nano, which does not have a corresponding script

Exiting
jetbot@jetbot:~/rootOnUSB$ `

Would you please take a look on this error? I am already using the vL4T32.1 release. I am using the image downloaded from JetBot WIKI website. Thanks a lot!

**Comment by bspwnmaster** [comment]
Ran into this issue as well and found the fix. The problem is with the buildKernelAndModules repo. When running  ./buildKernel.sh in the rootOnUSB repo, it downloads the latest version of buildKernelAndModules repo which isn't compatible with vL4T32.1. My fix was running the ./buildKernel.sh script, getting the error, going into the buildKernelAndModules repo, running git checkout vL4T32.1, and running the ./buildKernel.sh script again. Hope this helps.

**Comment by wikpunGitHub** [comment]
Thanks a lot! Your solution is also working for me.
